package ar.unrn.parcial.emailServices;

import java.time.LocalDateTime;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import ar.unrn.parcial.modelo.Observer;

public class ObserverVentasEmailSender implements Observer {

	@Override
	public void actualizar(String email, int cantidad, String descripcion, Double montoTotal, LocalDateTime fecha)
			throws MessagingException {
		// Put recipient’s address
		String to = email;

		// Put sender’s address
		// String from = "from@example.com";
		final String username = "5073f6cdd71bde";// username generated by Mailtrap
		final String password = "fcfc0636ac8f16";// password generated by Mailtrap

		// Paste host address from the SMTP settings tab in your Mailtrap Inbox
		String host = "smtp.mailtrap.io";

		Properties props = new Properties();
		props.put("mail.smtp.auth", "true");

		props.put("mail.smtp.host", host);
		props.put("mail.smtp.port", "2525");// use one of the options in the SMTP settings tab in your Mailtrap Inbox

		// Get the Session object.

		// Get the Session object.
		Session session = Session.getInstance(props, new javax.mail.Authenticator() {
			@Override
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(username, password);
			}
		});

		Message message = new MimeMessage(session);

		// Set Subject: header field
		message.setSubject("My first message with JavaMail");

		message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));

		// Put the content of your message
		message.setText("Fecha de Venta: " + fecha.getDayOfMonth() + "/" + fecha.getMonthValue() + "/" + fecha.getYear()
				+ " Cantidad de Remeras: " + cantidad + " Monto Total: " + montoTotal);

		// Send message
		Transport.send(message);

	}

}
